import sqlite3
import os
from contextlib import contextmanager
from typing import Generator
from backend.config import settings
from backend.utils.logger import logger

def get_db_connection() -> sqlite3.Connection:
    """
    Creates and returns a new raw SQLite database connection.
    Enables foreign keys and sets row factory for dict-like rows.
    """
    try:
        # Guarantee parent directory exists before establishing connection
        os.makedirs(os.path.dirname(settings.DB_PATH), exist_ok=True)
        
        conn = sqlite3.connect(settings.DB_PATH)
        
        # Enforce foreign key constraints (disabled by default in SQLite)
        conn.execute("PRAGMA foreign_keys = ON;")
        
        # Configure connection to return row objects that act like dictionaries
        conn.row_factory = sqlite3.Row
        
        return conn
    except sqlite3.Error as e:
        logger.error("Failed to connect to SQLite database", extra={"db_path": settings.DB_PATH, "error": str(e)})
        raise

@contextmanager
def transaction() -> Generator[sqlite3.Connection, None, None]:
    """
    Context manager for database operations to guarantee transactions.
    Automatically commits changes or rolls back on exception, then closes the connection.
    Usage:
        with transaction() as conn:
            conn.execute("INSERT INTO...")
    """
    conn = get_db_connection()
    try:
        yield conn
        conn.commit()
    except Exception as e:
        conn.rollback()
        logger.error("Database transaction rolled back due to error", extra={"error": str(e)})
        raise
    finally:
        conn.close()

def init_db() -> None:
    """
    Creates tables if they do not exist.
    Initializes standard relational schema: trends, analyses, and generated_content.
    """
    logger.info("Initializing SQLite database and verifying tables...", extra={"db_path": settings.DB_PATH})
    
    with transaction() as conn:
        # 1. Create raw trends table
        # external_id is unique to prevent duplicate fetching of the same RSS items
        conn.execute("""
            CREATE TABLE IF NOT EXISTS trends (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                source TEXT NOT NULL, -- 'reddit', 'google_trends'
                url TEXT,
                external_id TEXT UNIQUE NOT NULL, -- Unique hash of URL/ID to prevent duplicate imports
                raw_data TEXT, -- JSON serialization of entire fetched metadata
                created_at TEXT DEFAULT (datetime('now'))
            );
        """)

        # 2. Create trend analyses table
        # One-to-one mapping with trends (each trend has exactly one analysis)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS analyses (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trend_id INTEGER UNIQUE NOT NULL,
                engagement_score INTEGER NOT NULL, -- 0 to 100 rating
                sentiment TEXT NOT NULL,           -- e.g. Positive, Negative, Neutral
                angle TEXT NOT NULL,               -- e.g. Controversy, Educational, Industry News
                niche TEXT NOT NULL,               -- e.g. AI, Programming, FinTech
                summary TEXT NOT NULL,             -- Detailed summary generated by Gemini
                analysis_raw TEXT,                 -- Raw JSON payload returned by Gemini
                created_at TEXT DEFAULT (datetime('now')),
                FOREIGN KEY (trend_id) REFERENCES trends (id) ON DELETE CASCADE
            );
        """)

        # 3. Create platform-specific generated content table
        # One-to-many relationship: A trend can have multiple post drafts (LinkedIn, X, Medium)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS generated_content (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                trend_id INTEGER NOT NULL,
                platform TEXT NOT NULL,         -- 'linkedin', 'medium', 'x_summary'
                content_text TEXT NOT NULL,     -- Full generated markdown/text copy
                file_path TEXT,                 -- Path to locally exported file
                created_at TEXT DEFAULT (datetime('now')),
                FOREIGN KEY (trend_id) REFERENCES trends (id) ON DELETE CASCADE,
                UNIQUE(trend_id, platform)      -- Prevent duplicate drafts for the same trend/platform
            );
        """)
        
    logger.info("Database schema initialized successfully.")
